### ISSUE TITLE
clarify if i get the purpose of this plugin correct

### ISSUE THREAD

**Issue by throni3git** [mattjennings/vite-plugin-sveld#5]
hi, i want to know if this plugin (as an adapter for Vite) for creating Svelte typings with sveld for a) exporting a bunch of .d.ts files for serving my library or b) for direct usage of typings within Svelte components?

for my case (a), i am using _vite-plugin-dts_ to create typings for regular Typescript files. additionally, i'd like to type the Svelte components, but i don't get it running - there are no file outputs.

also, in `vite.config.ts` VSCode complains about missing types for `import sveld from "vite-plugin-sveld";`. i put the references triple slash directive in `vite.env.d.ts` but that didn't fix it.

**Comment by mattjennings** [comment]
It's essentially a shortcut for calling sveld's [ComponentParser](https://github.com/mattjennings/vite-plugin-sveld/blob/af7d35544058aa3caf2677f28c4b233c9527dfce/index.js#L21). It's not meant for generating types or anything like that.

You can check out the [playground project](https://github.com/mattjennings/vite-plugin-sveld/tree/main/playground) in this repo which serves as a basic example.
